base/urls.py
from django.urls import path, include

from base.views import UserCreateAPIView, LoginAuthToken

urlpatterns = [
    path('registro/', UserCreateAPIView.as_view(), name='usuario-create'),
    path('login/', LoginAuthToken.as_view(), name='usuario-login'),
]

consultorio/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from consultorio import views

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('logout/', views.logout_view, name='logout_user'),
    path('', views.dashboard_view, name='dashboard'),
    path('cliente/', include([
        path('', views.ClienteList.as_view(), name='dashboard-cliente'),
        path('estudios', views.ClienteEstudioList.as_view(), name='estudios-cliente'),
    ])),
    path('consultorio/', include([
        path('', views.ConsultorioDetail.as_view(), name='consultorio'),
        path('update/', views.ConsultorioUpdate.as_view(), name='consultorio-edit'),
    ])),
    path('estudio/', include([
        path('', views.EstudioList.as_view(), name='estudio'),
        path('create/', views.EstudioCreate.as_view(), name='estudio-create'),
        path('<int:estudio_id>/', include([
            path('edit/', views.EstudioUpdate.as_view(), name='estudio-edit'),
            path('delete/', views.EstudioDelete.as_view(), name='estudio-delete'),
        ])),
    ])),
    path('usuarios/', include([
        path('confirmar-reset-password/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
             name='password-reset-confirm'),
        path('completado-reset-password/', auth_views.PasswordResetCompleteView.as_view(
                template_name='consultorio/usuario/password_reset_complete.html'
            ), name='password-reset-complete'),
        path('change-password/', views.UserPasswordChangeView.as_view(), name='cambiar-pass'),
        path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='consultorio/usuario/password_change_done.html'
        ), name="password-change-done"),
        path('', views.UsuarioList.as_view(), name='usuarios'),
        path('create/', views.UsuarioCreate.as_view(), name='usuarioconsultorio-create'),
        path('create-paciente/', views.UsuarioPacienteCreate.as_view(), name='usuariopaciente-create'),
        path('<int:usuario_id>/', include([
            path('edit/', views.UsuarioUpdate.as_view(), name='usuarioconsultorio-edit'),
            path('delete/', views.UsuarioDelete.as_view(), name='usuarioconsultorio-delete'),
        ])),
    ])),
    path('tipoestudio/', include([
        path('', views.TipoEstudioList.as_view(), name='tipoestudio'),
        path('create/', views.TipoEstudioCreate.as_view(), name='tipoestudio-create'),
        path('<int:tipoestudio_id>/', include([
            path('edit/', views.TipoEstudioUpdate.as_view(), name='tipoestudio-edit'),
            path('delete/', views.TipoEstudioDelete.as_view(), name='tipoestudio-delete'),
        ])),
    ])),
    path('servicios/', include([
        path('', views.ServiceList.as_view(), name='service'),
        path('create/', views.ServiceCreate.as_view(), name='service-create'),
        path('<int:service_id>/', include([
            path('edit/', views.ServiceUpdate.as_view(), name='service-edit'),
            path('delete/', views.ServiceDelete.as_view(), name='service-delete'),
        ])),
    ])),
    path('laboratorios/', include([
        path('', views.LaboratorioList.as_view(), name='laboratorios'),
        path('create/', views.LaboratorioCreate.as_view(), name='laboratorio-create'),
        path('<int:laboratorio_id>/', include([
            path('edit/', views.LaboratorioUpdate.as_view(), name='laboratorio-edit'),
            path('delete/', views.LaboratorioDelete.as_view(), name='laboratorio-delete'),
        ])),
    ])),
    path('pacientes/', include([
        path('', views.PacientesList.as_view(), name='pacientes'),
        path('create/', views.PacienteCreate.as_view(), name='paciente-create'),
        path('<int:paciente_id>/', include([
            path('', views.PacienteDetail.as_view(), name='paciente'),
            path('edit/', views.PacienteUpdate.as_view(), name='paciente-edit'),
            path('delete/', views.PacienteDelete.as_view(), name='paciente-delete'),
            path('consulta/', include([
                path('', views.PacienteConsultaList.as_view(), name='paciente-consultas'),
                path('create/', views.PacienteConsultaCreate.as_view(), name='paciente-consulta-create'),
                path('<int:consulta_id>/', include([
                    path('', views.PacienteConsultaDetail.as_view(), name='paciente-consulta'),
                    path('edit/', views.PacienteConsultaUpdate.as_view(), name='paciente-consulta-edit'),
                    path('delete/', views.PacienteConsultaDelete.as_view(), name='paciente-consulta-delete'),
                ])),
            ])),
            path('estudios/', include([
                path('', views.PacienteEstudioList.as_view(), name='paciente-estudio'),
                path('create/', views.PacienteEstudioCreate.as_view(), name='paciente-estudio-create'),
                path('<int:estudio_id>/', include([
                    path('edit/', views.PacienteEstudioUpdate.as_view(), name='paciente-estudio-edit'),
                    path('delete/', views.PacienteEstudioDelete.as_view(), name='paciente-estudio-delete'),
                ])),
            ])),
        ])),
    ])),
    path('archivo-consulta/<int:archivo_id>/<int:paciente_id>/<int:consulta_id>', views.ArchivoConsultaDelete.as_view(),
         name='archivo-consulta-delete'),
    path('api/', include([
        path('auth/', include('base.urls')),
        # path('paciente/', include([
        #     path('', PacienteList.as_view(), name='paciente-list'),
        #     path('create/', PacienteCreate.as_view(), name='paciente-create'),
        #     path('update/', PacienteUpdate.as_view(), name='paciente-update'),
        # ])),
        # path('local/', include([
        # ])),
    ])),
]

virtualclinic/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from virtualclinic import settings

schema_view = get_schema_view(
   openapi.Info(
      title="Virtualclinic API",
      default_version='v1',
      description="API de virtualclinic",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinicadmin/', include('consultorio.urls')),
    path('', TemplateView.as_view(template_name="consultorio/landing.html")),
    path('', include('admin_material.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('appointment/', include('appointment.urls')),
]

handler400 = "base.views.handler400"
handler403 = "base.views.handler403"
handler404 = "base.views.handler404"
handler500 = "base.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consultorio/models.py
from django.db import models
from django.utils import timezone

from base.models import Usuario
from consultorio.constants import SEX


class Consultorio(models.Model):
    nombre = models.CharField(max_length=250)
    ruc = models.CharField(max_length=20, null=True, blank=True)
    razon_social = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    direccion = models.TextField('Dirección', null=True, blank=True)
    ubicacion = models.URLField('Ubicación maps', null=True, blank=True)
    telefono = models.CharField('Número de teléfono', max_length=80, null=True, blank=True)
    telefono_urgencia = models.CharField('Teléfono urgencia', max_length=80, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Paciente(models.Model):
    nombre = models.CharField('Nombre', max_length=50)
    apellido = models.CharField('Apellido', max_length=50)
    nombre_completo = models.CharField('Nombre y apellido', max_length=100)
    sexo = models.CharField(max_length=12, choices=SEX)
    fecha_nacimiento = models.DateField('Fecha de nacimiento', null=True, blank=True)
    nro_telefono = models.CharField('Número de teléfono', max_length=80, null=True, blank=True)
    email = models.EmailField('Email', blank=True, null=True)
    consultorio = models.ForeignKey(Consultorio, related_name='pacientes', null=True, blank=True,
                                    on_delete=models.SET_NULL)
    usuario = models.OneToOneField(Usuario, related_name='paciente', null=True, blank=True, on_delete=models.SET_NULL)
    nro_documento = models.CharField('Número de documento', max_length=80, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre_completo}".strip()

    def estudios_totales(self):
        total_estudios = 0
        for estudio in self.estudios.all():
            total_estudios += 1
        return total_estudios

    def save(self, *args, **kwargs):
        self.nombre_completo = self.nombre + ' ' + self.apellido
        super().save(*args, **kwargs)


class Consulta(models.Model):
    fecha = models.DateTimeField(default=timezone.now)
    observacion = models.TextField('Observación', null=True, blank=True)
    proxima_consulta = models.DateTimeField('Próxima consulta', null=True, blank=True)
    receta = models.TextField('Receta', null=True, blank=True)
    receta_foto = models.ImageField('Receta Foto', null=True, blank=True)
    paciente = models.ForeignKey(Paciente, related_name='consultas', on_delete=models.CASCADE)
    creado_por = models.ForeignKey(Usuario, related_name='consultas_creados', on_delete=models.SET_NULL,
                                   null=True, blank=True)
    actualizado_por = models.ForeignKey(Usuario, related_name='consultas_actualizados', on_delete=models.SET_NULL,
                                        null=True, blank=True)

    def __str__(self):
        return str(self.fecha) + ' ' + str(self.paciente)


class ArchivoConsulta(models.Model):
    consulta = models.ForeignKey(Consulta, related_name='archivos', on_delete=models.CASCADE)
    archivo = models.FileField()

    def __str__(self):
        return str(self.archivo)


class TipoEstudio(models.Model):
    tipo = models.CharField('Tipo de estudio', max_length=200)
    consultorio = models.ForeignKey(Consultorio, related_name='tipos_estudios', null=True, blank=True,
                                    on_delete=models.SET_NULL)

    def __str__(self):
        return self.tipo


class Laboratorio(models.Model):
    nombre = models.CharField('Nombre laboratorio', max_length=250)
    direccion = models.TextField('Dirección', null=True, blank=True)
    telefono = models.CharField('Número de teléfono', max_length=80, null=True, blank=True)
    doctor_encargado = models.CharField('Nombre encargado', max_length=100, null=True, blank=True)
    consultorio = models.ForeignKey(Consultorio, related_name='laboratorios', null=True, blank=True,
                                    on_delete=models.SET_NULL)

    def __str__(self):
        return self.nombre


class Estudio(models.Model):
    fecha = models.DateTimeField('Fecha estudio', default=timezone.now)
    proxima_consulta = models.DateTimeField(null=True, blank=True)
    notificado = models.BooleanField(default=False)
    resultado = models.FileField(null=True, blank=True)
    paciente = models.ForeignKey(Paciente, related_name='estudios', on_delete=models.CASCADE)
    tipo_estudio = models.ForeignKey(TipoEstudio, related_name='estudios', on_delete=models.PROTECT)
    laboratorio = models.ForeignKey(Laboratorio, related_name='estudios', null=True, blank=True, on_delete=models.SET_NULL)
    creado_por = models.ForeignKey(Usuario, related_name='estudios_creados', on_delete=models.SET_NULL,
                                   null=True, blank=True)
    actualizado_por = models.ForeignKey(Usuario, related_name='estudios_actualizados', on_delete=models.SET_NULL,
                                        null=True, blank=True)

    def __str__(self):
        return str(self.fecha) + ' ' + str(self.tipo_estudio) + ' ' + str(self.paciente)

templates/consultorio/paciente/add.html
{% extends "layouts/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    {% if object %}
        Editar Paciente
    {% else %}
        Agregar Paciente
    {% endif %}
{% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item text-sm text-dark ms-2"><a href="{% url 'pacientes' %}">Pacientes</a></li>
{% if object %}
    <li class="breadcrumb-item active text-sm text-dark ms-2" aria-current="page">Editar paciente {{ object.nombre_completo }}</li>
{% else %}
    <li class="breadcrumb-item active text-sm text-dark ms-2" aria-current="page">Agregar Paciente</li>
{% endif %}
{% endblock breadcrumb %}
{% block content %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card my-4">
                <div class="card-header bg-primary py-3">
                    <h6 class="text-white text-uppercase m-0">
                        {% if object %}
                            Editar Paciente
                        {% else %}
                            Agregar Paciente
                        {% endif %}
                    </h6>
                </div>
                <div class="card-body">
                    <form method="post" class="row g-3" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ field.label_tag }}
                                {{ field|add_class:"form-control border px-3 py-2" }}
                            </div>
                            <span class="text-danger">{{ field.errors }}</span>
                        </div>
                        {% endfor %}
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Guardar
                                {% else %}
                                    Agregar Paciente
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var labels = document.getElementsByTagName("label");
        for (var i = 0; i < labels.length; i++) {
            if(["Consultorio:"].includes(labels[i].innerHTML)){
                labels[i].classList.add("visually-hidden");
            }
        }
    });
</script>
{% endblock content %}

templates/consultorio/paciente/delete.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %} Confirmar Eliminación {% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item text-sm text-dark ms-2"><a href="{% url 'pacientes' %}">Pacientes</a></li>
<li class="breadcrumb-item active text-sm text-dark ms-2" aria-current="page">Eliminar Paciente {{ object.nombre_completo }}</li>
{% endblock breadcrumb %}
{% block content %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card my-4">
                <div class="card-header bg-danger py-3">
                    <h6 class="text-white text-uppercase m-0">Confirmar Eliminación</h6>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ confirm_delete_form.paciente_id }}
                        <p>¿Estás seguro de que deseas eliminar al paciente "{{ object.nombre_completo }}"?</p>
                        <p>Información del paciente:</p>
                        <ul>
                            <li>Nombre: {{ object.nombre_completo }}</li>
                            <li>Nro. documento: {{ object.nro_documento }}</li>
                        </ul>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                        <a href="{% url 'pacientes' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/consultorio/paciente/detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %}
    Detalle de Paciente - {{ paciente.nombre_completo }}
{% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item text-sm text-dark ms-2"><a href="{% url 'pacientes' %}">Pacientes</a></li>
<li class="breadcrumb-item active text-sm text-dark ms-2" aria-current="page">{{ paciente.nombre_completo }}</li>
{% endblock breadcrumb %}
{% block content %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card my-4">
                <div class="card-header bg-primary py-3">
                    <div class="row bg-primary border-radius-lg">
                        <div class="col-9">
                            <h6 class="text-white text-capitalize ps-3">Detalle de Paciente - {{ paciente.nombre_completo }}</h6>
                        </div>
                        <div class="col-3">
                            <a href="{% url 'paciente-edit' paciente.pk %}" class="btn btn-light">
                            <i class="material-icons">edit</i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h4>Información del Paciente</h4>
                    <div class="row">
                        <div class="col-6">
                            <p><strong>Nombre:</strong> {{ paciente.nombre_completo }}</p>
                            <p><strong>Nro. telefono:</strong> {{ paciente.nro_telefono|default:"-" }}</p>
                            <p><strong>Nro. documento:</strong> {{ paciente.nro_documento|default:"-" }}</p>
                            <p><strong>Sexo:</strong> {{ paciente.get_sexo_display }}</p>
                            <p><strong>Fecha de nacimiento:</strong> {{ paciente.fecha_nacimiento|default:"-" }}</p>
                        </div>
                        <div class="w-100 d-md-none mt-3"></div>
                        <div class="d-grid col-6 mx-auto">
                            <a href="{% url 'paciente-consultas' paciente.pk %}" class="btn btn-outline-primary align-self-center" role="button">Consultas <i class="material-icons">medical_services</i></a>
                            <a href="{% url 'paciente-estudio' paciente.pk %}" class="btn btn-outline-primary align-self-center" role="button">Estudios <i class="material-icons">science</i></a>
                        </div>
                    </div>
                    {%if consultas%}
                    <div class="row">
                        <div class="accordion" id="accordionExample1">
                          <div class="accordion-item">
                            <h2 class="accordion-header bg-light border p-2" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Resumen de consultas
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708"/>
                                </svg>
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample1">
                              <div class="accordion-body overflow-auto px-2" style="max-height: 200px;">
                                  {%for consulta in consultas %}
                                    <strong class="text-dark">{{consulta.fecha}}</strong>
                                    <p class="text-dark">{{consulta.observacion}}</p>
                                  {%endfor%}
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/consultorio/paciente/list.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %} Pacientes {% endblock title %}
{% block breadcrumb %}
<li class="breadcrumb-item active text-sm text-dark ms-2" aria-current="page">Pacientes</li>
{% endblock breadcrumb %}
{% block content %}
<div class="container-fluid py-4">
    <div id="liveAlertPlaceholder"></div>
    {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible text-white" role="alert">
            <span class="text-sm">{{message}}</span>
            <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-danger alert-dismissible text-white" role="alert">
            <span class="text-sm">{{message}}</span>
            <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-1 z-index-2">
                    <div class="row bg-primary shadow-dark border-radius-lg pt-4 pb-3">
                        <div class="col-9">
                            <h6 class="text-white text-capitalize ps-3">Pacientes</h6>
                        </div>
                        <div class="col-3">
                            <a href="{% url 'paciente-create' %}" class="btn btn-light">
                            <i class="material-icons">add</i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body px-2 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table table-striped" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Nro. telefono</th>
                                    <th>Nro. documento</th>
                                    <th>Sexo</th>
                                    <th>Email</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for paciente in pacientes %}
                                <tr>
                                    <td>{{ paciente.nombre_completo }}</td>
                                    <td>{{ paciente.nro_telefono|default:"-" }}</td>
                                    <td>{{ paciente.nro_documento|default:"-" }}</td>
                                    <td>{{ paciente.get_sexo_display }}</td>
                                    <td>{{ paciente.email|default:"-" }}</td>
                                    <td>
                                        <a title="Detalle" href="{% url 'paciente' paciente.pk %}" class="btn btn-primary"><i class="material-icons">visibility</i></a>
                                        <a title="Editar" href="{% url 'paciente-edit' paciente.pk %}" class="btn btn-info"><i class="material-icons">edit</i></a>
                                        {% if not paciente.usuario %}
                                            {% if user.groups.all.0.name == "Administrador" %}
                                                <button onclick="setValues('{{paciente.email|default:''}}', '{{paciente.nombre}}', '{{paciente.apellido}}', '{{paciente.nro_documento|default:''}}', '{{paciente.nro_telefono|default:''}}', {{paciente.id}})" type="button" title="Crear usuario" {% if paciente.email %} data-bs-toggle="modal" data-bs-target="#exampleModal" {% endif %} class="btn btn-success"><i class="material-icons">person_add</i></button>
                                            {%endif%}
                                        {% endif %}
                                        {% if user.groups.all.0.name == "Administrador" %}<a title="Borrar" href="{% url 'paciente-delete' paciente.pk %}" class="btn btn-danger"><i class="material-icons">delete</i></a>{%endif%}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/custom-footer.html' %}
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Crear usuario a Paciente</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <form id="formCrear" action="{% url 'usuariopaciente-create' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="id_username" class="col-form-label">Username:</label>
                        <input type="text" class="form-control border px-3 py-2" id="id_username" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="id_email" class="col-form-label">Email:</label>
                        <input readonly type="email" class="form-control border px-3 py-2" id="id_email" name="email"/>
                    </div>
                    <input type="hidden" id="id_first_name" name="first_name"/>
                    <input type="hidden" id="id_last_name" name="last_name"/>
                    <input type="hidden" id="id_nro_documento" name="nro_documento"/>
                    <input type="hidden" id="id_nro_telefono" name="nro_telefono"/>
                    <input type="hidden" id="id_paciente" name="paciente_id"/>
                </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success">Registrar</button>
              </div>
            </form>
        </div>
      </div>
    </div>
</div>
<script>
    function setValues(email, firstName, lastName, nroDocumento, nroTelefono, pacienteId) {
        if(email){
            document.getElementById("id_email").value = email;
            document.getElementById("id_username").value = email;
            document.getElementById("id_first_name").value = firstName;
            document.getElementById("id_last_name").value = lastName;
            document.getElementById("id_nro_documento").value = nroDocumento;
            document.getElementById("id_nro_telefono").value = nroTelefono;
            document.getElementById("id_paciente").value = pacienteId;
        } else {
            appendAlert('Debe setear email al usuario', 'warning')
        }
    }
    const alertPlaceholder = document.getElementById('liveAlertPlaceholder')
        const appendAlert = (message, type) => {
        const wrapper = document.createElement('div')
        wrapper.innerHTML = [
        `<div class="alert alert-${type} alert-dismissible" role="alert">`,
        `   <div><span class="text-sm text-white">${message}</span></div>`,
        '   <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
        '</div>'
        ].join('')

        alertPlaceholder.append(wrapper)
    }
</script>
{% endblock content %}